### ISSUE TITLE
module 'numpy' has no attribute 'bool'

### ISSUE THREAD

**Issue by lecrabe** [sepal-contrib/sbae_point_analysis#9]
Libraries dont load, with this error coming from the BFAST package

AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

**Comment by 12rambau** [comment]
To be fully compliant with the current (and more importantly future) environment of SEPAL @BuddyVolly is working on a lib that will be installed in SEPAL venvs. In the meantime you can try to  downgrade the version of numpy installed to 1.21 or 1.20, I don't see in their documentation when they dropped the support for bool

**Comment by 12rambau** [comment]
I checked with @aurelgrooves, the combination runs just fine:

```
numpy==1.20.1
pandas==1.4.4
```
